// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeFq1v9w_bMLykqMCzaI24joXyizC7mTw',
    appId: '1:96865113961:web:5ed7344afba00e09620ff8',
    messagingSenderId: '96865113961',
    projectId: 'starry-sunup-503314-q3',
    authDomain: 'starry-sunup-503314-q3.firebaseapp.com',
    storageBucket: 'starry-sunup-503314-q3.firebasestorage.app',
    measurementId: 'G-GL419RNKQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMV6pBNSFEi9bDI9jZzBUHSpw6MhuUqFk',
    appId: '1:96865113961:android:472d5bc917816a54620ff8',
    messagingSenderId: '96865113961',
    projectId: 'starry-sunup-503314-q3',
    storageBucket: 'starry-sunup-503314-q3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzses07OmLJsfhcLEJnFGwTE-kd9hM2eU',
    appId: '1:96865113961:ios:e2ff52d484b0c286620ff8',
    messagingSenderId: '96865113961',
    projectId: 'starry-sunup-503314-q3',
    storageBucket: 'starry-sunup-503314-q3.firebasestorage.app',
    iosBundleId: 'dev.joshdev.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzses07OmLJsfhcLEJnFGwTE-kd9hM2eU',
    appId: '1:96865113961:ios:e2ff52d484b0c286620ff8',
    messagingSenderId: '96865113961',
    projectId: 'starry-sunup-503314-q3',
    storageBucket: 'starry-sunup-503314-q3.firebasestorage.app',
    iosBundleId: 'dev.joshdev.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeFq1v9w_bMLykqMCzaI24joXyizC7mTw',
    appId: '1:96865113961:web:f090f1744ba2d404620ff8',
    messagingSenderId: '96865113961',
    projectId: 'starry-sunup-503314-q3',
    authDomain: 'starry-sunup-503314-q3.firebaseapp.com',
    storageBucket: 'starry-sunup-503314-q3.firebasestorage.app',
    measurementId: 'G-TZZCCWZL3Q',
  );
}
